### ISSUE TITLE
setType in Domain objects

### ISSUE THREAD

**Issue by sagikazarmark** [psecio/jwt#15]
I find it odd that you are able to set the type for domain objects (Issuer, etc). Wouldn't it be better to move the setType to the Custom object, so that it is the only one which can be modified? Even better to make it an immutable object, and set the type in constructor

**Comment by enygma** [comment]
Hmm, good point - you should never be able to change those base ones defined in the spec. Good catch.

**Comment by enygma** [comment]
Moved this over so only Custom claims can set the type. thanks!
