### ISSUE TITLE
Audience should be optional

### ISSUE THREAD

**Issue by mediamonks-robert** [psecio/jwt#16]
Currently the "audience" field is mandatory:

    if (!isset($claims->aud) || empty($claims->aud)) {
        throw new Exception\DecodeException('Audience not defined [aud]');
    }

According to the spec this should be optional: https://tools.ietf.org/html/draft-ietf-oauth-json-web-token-32#section-4.1.3

**Comment by enygma** [comment]
This has been changed and is updated in release 1.7. Thanks!

**Comment by mediamonks-robert** [comment]
Great, thanks :)
