### ISSUE TITLE
Timing vulnerability in MAC verification

### ISSUE THREAD

**Issue by ircmaxell** [psecio/jwt#8]
The current [MAC verification code](https://github.com/psecio/jwt/blob/master/src/Psecio/Jwt/Jwt.php#L175) is vulnerable to timing attacks since it uses a direct comparison.

Instead, implement [Double HMAC Verification](https://www.isecpartners.com/blog/2011/february/double-hmac-verification.aspx)

However, don't re-use any keys, generate a random key for use in the verification: [source](https://github.com/defuse/php-encryption/issues/21):

    function timingSafeEquals($m1, $m2) {
        $key = gen_random(32);
        if (hash_hmac('sha256', $m1, $key, true) === hash_hmac('sha256', $m2, $key, true)) {
            return true;
        }
        return false;
    }

**Comment by sagikazarmark** [comment]
If I am correct, than `hash_equals` is the solution for this. Since it is introduced in PHP 5.6, I created a backport package for it:

https://github.com/indigophp/hash-compat

**Comment by enygma** [comment]
Adding a quick version of hash_equals to the Jwt class to backport the validation. Closing issue.
